from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from app.domain.models import TradeEntry, Profile
import io

class DocumentService:
    def generate_form_m(self, entry: TradeEntry, profile: Profile) -> io.BytesIO:
        buffer = io.BytesIO()
        c = canvas.Canvas(buffer, pagesize=A4)
        
        c.setFont("Helvetica-Bold", 16)
        c.drawString(1 * inch, 11 * inch, "NIGERIAN SINGLE WINDOW - FORM M DRAFT")
        
        c.setFont("Helvetica", 10)
        c.line(0.5 * inch, 10.8 * inch, 8 * inch, 10.8 * inch)
        
        c.drawString(1 * inch, 10.5 * inch, f"Exporter/Importer: {profile.business_name or 'N/A'}")
        c.drawString(1 * inch, 10.3 * inch, f"TIN: {profile.tin or 'N/A'}")
        c.drawString(1 * inch, 10.1 * inch, f"CAC: {profile.cac_number or 'N/A'}")
        
        c.line(0.5 * inch, 9.9 * inch, 8 * inch, 9.9 * inch)
        
        c.setFont("Helvetica-Bold", 12)
        c.drawString(1 * inch, 9.6 * inch, "PRODUCT DETAILS")
        
        c.setFont("Helvetica", 10)
        c.drawString(1 * inch, 9.3 * inch, f"Description: {entry.product_name}")
        c.drawString(1 * inch, 9.1 * inch, f"HS Code: {entry.hs_code or 'Pending'}")
        c.drawString(1 * inch, 8.9 * inch, f"Quantity: {entry.quantity} {entry.unit}")
        c.drawString(1 * inch, 8.7 * inch, f"FOB Value: ${entry.value_usd}")
        
        c.line(0.5 * inch, 8.4 * inch, 8 * inch, 8.4 * inch)
        
        c.setFont("Helvetica-Oblique", 8)
        c.drawString(1 * inch, 1 * inch, "Generated by KodaTrade - AI Trade Co-Pilot")
        
        c.showPage()
        c.save()
        
        buffer.seek(0)
        return buffer

document_service = DocumentService()
